service:
  name: sample-solution
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: 
        'Fn::Join':
          - ''
          - - 'arn:aws:dynamodb:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':table/${self:service.name}-item'
  environment:
    TABLE_NAME: ${self:service.name}-item

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  Resources:
    ItemTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:service.name}-item
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
